//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zadacha2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentariy_tabel
    {
        public int ID { get; set; }
        public string Comentariy { get; set; }
        public int SotrudnicId { get; set; }
        public int OrderId { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual User User { get; set; }
    }
}
