//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zadacha2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDEntities : DbContext
    {
        private static BDEntities m_instance;

        public static BDEntities GetInstance()
        {
            if (m_instance == null) m_instance = new BDEntities();
            return m_instance;
        }
        public BDEntities()
            : base("name=BDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comentariy_tabel> Comentariy_tabel { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Orgtehnica> Orgtehnicas { get; set; }
        public virtual DbSet<Problem> Problems { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Zadacha_zapchast> Zadacha_zapchast { get; set; }
        public virtual DbSet<ZadachaZacasa> ZadachaZacasas { get; set; }
        public virtual DbSet<Zapchast> Zapchasts { get; set; }
    }
}
