//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zadacha2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zadacha_zapchast
    {
        public int ID { get; set; }
        public int ZadachaId { get; set; }
        public int ZapchastId { get; set; }
    
        public virtual ZadachaZacasa ZadachaZacasa { get; set; }
        public virtual Zapchast Zapchast { get; set; }
    }
}
